name: Build/release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  mac:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.x

      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: build mac Electron app
        run: pnpm electron:build:mac

      - name: Upload File
        uses: actions/upload-artifact@v4.3.6
        with:
          name: mac
          path: dist_electron
